require("paletas.remap")
require("paletas.theme")
require("paletas.packer")

print("Temporary Reminder, remove this soon-ish!")
print("<leader> is <space>, <C-> means Control")
print("<leader>pv for the file explorer")
print("<leader>pf for find files")
print("<leader>ps for grep files")
print("<C-p> for git find")
